# Generated by Django 4.1.6 on 2023-02-09 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_time', models.FloatField()),
                ('max_versions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('artifact_url', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('visible', models.BooleanField()),
                ('active', models.BooleanField()),
                ('build_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxford2.buildtype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxford2.category')),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxford2.parsertype')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxford2.project')),
            ],
        ),
        migrations.CreateModel(
            name='NavTreeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('item_url', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('visible', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxford2.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxford2.project')),
            ],
        ),
    ]
