# Generated by Django 4.1.6 on 2023-04-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxford2', '0002_config_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='footer_message',
            field=models.CharField(default='Powered by Tiur Docs.', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='start_page',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
